/**
 * villageBuildings.js — GENERATED by build-tools/import-village-art.mjs. Do not edit.
 *
 * Village Add-on buildings and housing tiers, by DISPLAY NAME.
 *
 * The live page shows a building only by its rendered name ("Voidiron Archive")
 * — the item key it is really keyed by ("construction_building_tier_11") never
 * reaches the DOM — so name is the only join available, and this map is
 * normalised (lower-case, collapsed whitespace) for that lookup.
 * VillagePanels.resolveBuilding() owns the read; a name that misses falls back
 * to a generic sigil rather than an empty medallion.
 *
 * Source of truth: assets/village/buildings.json (imported from the art source
 * repo's construction_icon_manifest.json). tests/village-panels.test.mjs pins
 * the two in step and checks every referenced asset file exists.
 */

/** @type {Readonly<Record<string, { tier: number, name: string, file: string }>>} */
export const VILLAGE_BUILDINGS = Object.freeze({
  "training yard": Object.freeze({ tier: 1, name: "Training Yard", file: "village/building_1.webp" }),
  "ironfang palisade": Object.freeze({ tier: 2, name: "Ironfang Palisade", file: "village/building_2.webp" }),
  "silverroot infirmary": Object.freeze({ tier: 3, name: "Silverroot Infirmary", file: "village/building_3.webp" }),
  "goldfire scriptorium": Object.freeze({ tier: 4, name: "Goldfire Scriptorium", file: "village/building_4.webp" }),
  "mythril countinghouse": Object.freeze({ tier: 5, name: "Mythril Countinghouse", file: "village/building_5.webp" }),
  "starsteel trophy hall": Object.freeze({ tier: 6, name: "Starsteel Trophy Hall", file: "village/building_6.webp" }),
  "obsidian greenhouse": Object.freeze({ tier: 7, name: "Obsidian Greenhouse", file: "village/building_7.webp" }),
  "runite war college": Object.freeze({ tier: 8, name: "Runite War College", file: "village/building_8.webp" }),
  "dragonfall rampart": Object.freeze({ tier: 9, name: "Dragonfall Rampart", file: "village/building_9.webp" }),
  "aether sanatorium": Object.freeze({ tier: 10, name: "Aether Sanatorium", file: "village/building_10.webp" }),
  "voidiron archive": Object.freeze({ tier: 11, name: "Voidiron Archive", file: "village/building_11.webp" }),
  "celestial exchange": Object.freeze({ tier: 12, name: "Celestial Exchange", file: "village/building_12.webp" }),
  "bloodstone reliquary": Object.freeze({ tier: 13, name: "Bloodstone Reliquary", file: "village/building_13.webp" }),
  "moonsteel arboretum": Object.freeze({ tier: 14, name: "Moonsteel Arboretum", file: "village/building_14.webp" }),
  "sunforge arena": Object.freeze({ tier: 15, name: "Sunforge Arena", file: "village/building_15.webp" }),
  "nethergate bastion": Object.freeze({ tier: 16, name: "Nethergate Bastion", file: "village/building_16.webp" }),
  "stormglass chapel of healing": Object.freeze({ tier: 17, name: "Stormglass Chapel of Healing", file: "village/building_17.webp" }),
  "kingsfall grand library": Object.freeze({ tier: 18, name: "Kingsfall Grand Library", file: "village/building_18.webp" }),
  "eternium treasury": Object.freeze({ tier: 19, name: "Eternium Treasury", file: "village/building_19.webp" }),
  "astral museum": Object.freeze({ tier: 20, name: "Astral Museum", file: "village/building_20.webp" }),
  "gravite botanical dome": Object.freeze({ tier: 21, name: "Gravite Botanical Dome", file: "village/building_21.webp" }),
  "frostiron warfront hall": Object.freeze({ tier: 22, name: "Frostiron Warfront Hall", file: "village/building_22.webp" }),
  "dusksteel citadel wall": Object.freeze({ tier: 23, name: "Dusksteel Citadel Wall", file: "village/building_23.webp" }),
  "titanium grand infirmary": Object.freeze({ tier: 24, name: "Titanium Grand Infirmary", file: "village/building_24.webp" }),
  "skysteel observatory": Object.freeze({ tier: 25, name: "Skysteel Observatory", file: "village/building_25.webp" }),
  "emberium mint": Object.freeze({ tier: 26, name: "Emberium Mint", file: "village/building_26.webp" }),
  "soulsteel vault of relics": Object.freeze({ tier: 27, name: "Soulsteel Vault of Relics", file: "village/building_27.webp" }),
  "chronite greenhouse spire": Object.freeze({ tier: 28, name: "Chronite Greenhouse Spire", file: "village/building_28.webp" }),
  "worldforge coliseum": Object.freeze({ tier: 29, name: "Worldforge Coliseum", file: "village/building_29.webp" }),
  "voidglass bulwark": Object.freeze({ tier: 30, name: "Voidglass Bulwark", file: "village/building_30.webp" }),
  "thalassic sanctum of tides": Object.freeze({ tier: 31, name: "Thalassic Sanctum of Tides", file: "village/building_31.webp" }),
  "ashspire hall of records": Object.freeze({ tier: 32, name: "Ashspire Hall of Records", file: "village/building_32.webp" }),
  "glacirite royal treasury": Object.freeze({ tier: 33, name: "Glacirite Royal Treasury", file: "village/building_33.webp" }),
  "primordial wonder": Object.freeze({ tier: 34, name: "Primordial Wonder", file: "village/building_34.webp" }),
});

/** @type {Readonly<Record<string, { tier: number, name: string, file: string }>>} */
export const VILLAGE_HOUSES = Object.freeze({
  "camp": Object.freeze({ tier: 1, name: "Camp", file: "village/house_1.webp" }),
  "cottage": Object.freeze({ tier: 2, name: "Cottage", file: "village/house_2.webp" }),
  "villa": Object.freeze({ tier: 3, name: "Villa", file: "village/house_3.webp" }),
  "manor": Object.freeze({ tier: 4, name: "Manor", file: "village/house_4.webp" }),
  "citadel": Object.freeze({ tier: 5, name: "Citadel", file: "village/house_5.webp" }),
});
