/**
 * zoneThemes.js — GENERATED by build-tools/import-skill-themes.mjs. Do not edit.
 *
 * Maps an IdleWorlds zone number to one of the nine environment frame themes.
 * Source of truth: assets/skills-ui/zone-theme-map.json (imported from the
 * sibling sprites repo). HeaderRenderer.applyZoneTheme() reads this to pick the
 * per-zone atlas, corner filigree and separator flourish; tests/zone-themes.test.mjs
 * pins the generated map in step and checks every referenced asset file exists.
 */

export const ZONE_THEMES = Object.freeze({
  1: 'verdant',
  2: 'forged-metal',
  3: 'verdant',
  4: 'infernal',
  5: 'forged-metal',
  6: 'celestial',
  7: 'voidborn',
  8: 'runic-arcane',
  9: 'infernal',
  10: 'celestial',
  11: 'voidborn',
  12: 'celestial',
  13: 'infernal',
  14: 'lunar-spectral',
  15: 'infernal',
  16: 'infernal',
  17: 'tempest-oceanic',
  18: 'runic-arcane',
  19: 'voidborn',
  20: 'voidborn',
  21: 'runic-arcane',
  22: 'glacial',
  23: 'lunar-spectral',
  24: 'forged-metal',
  25: 'celestial',
  26: 'infernal',
  27: 'lunar-spectral',
  28: 'runic-arcane',
  29: 'infernal',
  30: 'voidborn',
  31: 'tempest-oceanic',
  32: 'infernal',
  33: 'glacial',
  34: 'verdant',
});

export const THEME_NAMES = Object.freeze([
  'celestial',
  'forged-metal',
  'glacial',
  'infernal',
  'lunar-spectral',
  'runic-arcane',
  'tempest-oceanic',
  'verdant',
  'voidborn',
]);

export function zoneTheme(zone) {
  return (Number.isInteger(zone) && ZONE_THEMES[zone]) || null;
}
